[package]
name = "dow"
description = "Tomohiko Sakamoto's algorithm for finding the day of the week"
version = "0.1.0"
license = "MIT"
authors = ["Daniel Lockyer <thisisdaniellockyer@gmail.com>"]
repository = "https://github.com/neosilky/dow"
